EXEC sp_help fact
--1. Display the number of states present in the LocationTable
use alabs_skills
SELECT state 
from [Location]
-- 2.How many products are of regular type?
select * from Product
select * from [Location]
SELECT * from fact
select COUNT([Type]) as Total_regular_type
from Product
where [Type] LIKE ('%Regular%')

-- 3. How much spending has been done on marketing of product ID 1?
SELECT sum(marketing)
from fact
WHERE ProductId=1

-- 4. What is the minimum sales of a product?
SELECT MIN(Sales)
from fact

-- 5. Display the max Cost of Good Sold (COGS).
SELECT max(cogs) as maximum_cogs
from fact

-- 6. Display the details of the product where product type is coffee.

select *
from Product
WHERE Product_Type = 'coffee'

-- 7. Display the details where total expenses are greater than 40.

select *
from fact
where Total_Expenses > 40

-- 8. What is the average sales in area code 719?

select AVG(sales) AS Average_sales
from fact
WHERE Area_Code = 719

-- 9. Find out the total profit generated by Colorado state.

SELECT  State,  SUM(profit) as Total_profit, [Location].Area_Code 
from fact
INNER JOIN [Location] on fact.Area_Code = [Location].Area_Code
WHERE [State] = 'colorado'
GROUP BY [State], [Location].Area_Code

-- 10. Display the average inventory for each product ID.
SELECT AVG(inventory) average_inventory, ProductId
FROM fact
GROUP BY ProductId, Inventory

-- 11. Display state in a sequential order in a Location Table.

SELECT state 
from [Location]
ORDER BY [State] ASC 

-- 12. Display the average budget of the Product where the average budget margin should be greater than 100.

select product.ProductId, AVG(budget_sales) as average_margin
from fact
JOIN Product on fact.ProductId = Product.ProductId
GROUP BY Product
HAVING AVG(Budget_Margin)>100



SELECT 
    p.Product,
    AVG(f.[Budget Sales]) AS Avg_Budget
FROM fact f
JOIN Product p
    ON f.ProductId = p.ProductId
GROUP BY p.Product
HAVING AVG(f.[Budget Margin]) > 100;

-- 13. What is the total sales done on date 2010-01-01?
SELECT sales
from fact
where [Date] = '2010-01-01'

-- 14. Display the average total expense of each product ID on an individual date.

SELECT AVG(TOTAL_EXPENSES) average_total, ProductId, [Date]
from fact
GROUP BY date, ProductId

-- 15. Display the table with the following attributes such as date, productID, product_type, product, sales, profit, state, area_code.

SELECT fact.[Date], fact.Sales, fact.Profit, fact.Area_Code, fact.ProductId,  Product.Product_Type, Product.Product, [Location].[State]
from fact
LEFT JOIN Product on fact.ProductId = Product.ProductId
LEFT JOIN [Location] on fact.Area_Code = [Location].Area_Code

-- 12. Display the average budget of the Product where the average budget margin should be greater than 100.

select productid, avg(budget_sales) as Average_sales,
                  avg(budget_margin) as average_margin
                  from fact
group by ProductId
having avg(budget_margin) > 100

select * from fact