-- 7.	How many customers have >10 transactions with us, excluding returns?

WITH customer_transactions AS (

    SELECT 
        cust_id
    FROM Transactions
    WHERE total_amt > 0
    GROUP BY cust_id
    HAVING COUNT(transaction_id) > 10
)
SELECT COUNT(*) AS total_customers 
 FROM  customer_transactions

--  8.	What is the combined revenue earned from the 
-- “Electronics” & “Clothing” categories, from “Flagship stores”?

SELECT 
    SUM(t.total_amt) AS combined_revenue
FROM Transactions t
INNER JOIN prod_cat_info pi   
ON t.prod_cat_code = pi.prod_cat_code
AND t.prod_subcat_code = pi.prod_sub_cat_code
WHERE prod_cat IN ('Electronics', 'Clothing')
AND Store_type = 'Flagship Store'


-- 9.	What is the total revenue generated from “Male” customers in “Electronics” category? 
-- Output should display total revenue by prod sub-cat. 😀😀😀

SELECT 
    SUM(t.total_amt) AS total_revenue,
    pi.prod_subcat
FROM Customer c  
INNER JOIN Transactions t 
ON t.cust_id = c.customer_Id
INNER JOIN prod_cat_info pi 
ON t.prod_cat_code = pi.prod_cat_code
AND t.prod_subcat_code = pi.prod_sub_cat_code
WHERE c.Gender = 'Male'
AND pi.prod_cat = 'Electronics'
GROUP BY pi.prod_subcat


-- 10.	What is percentage of sales and returns by product sub category; 
-- display only top 5 sub categories in terms of sales?

SELECT top 5 
    pi.prod_cat,
    pi.prod_subcat,
    SUM(
        case 
            when t.total_amt > 0 then t.total_amt 
            else 0 
        END
    ) AS subcat_sales,

    SUM(
        CASE
            WHEN t.total_amt < 0 THEN ABS(t.total_amt)
            ELSE 0
        END
    ) AS subcat_returns,

    -- % sales within this subcategory

    SUM(
        CASE 
            WHEN t.total_amt > 0 then t.total_amt
            ELSE 0
        END
        ) / SUM(ABS(t.total_amt)) * 100 AS pct_sales_within_subcat,

    -- % returns within this category 

    SUM(
        case 
            when t.total_amt < 0 then ABS(t.total_amt)
            else 0 
        END ) / SUM(ABS(t.total_amt)) * 100 AS pct_returns_within_subcat 
FROM Transactions t  
INNER JOIN prod_cat_info pi 
    ON t.prod_cat_code = pi.prod_cat_code
    and t.prod_subcat_code = pi.prod_sub_cat_code
GROUP BY pi.prod_cat, pi.prod_subcat
ORDER BY subcat_sales DESC

-- 11.	For all customers aged between 25 to 35 years find what is the net total revenue 
-- generated by these consumers in last 30 days of transactions from max 
-- transaction date available in the data?

SELECT
    DATEDIFF()
FROM customer